name = "battle-city"
main = "worker/index.ts"
compatibility_date = "2026-04-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "GAME"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]
